
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 6;
  public static final int IN = 2;
  public static final int STRING_LITERAL = 12;
  public static final int PLUS = 11;
  public static final int EQ = 10;
  public static final int EOF = 0;
  public static final int IF = 3;
  public static final int ELSE = 4;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int RPAREN = 9;
  public static final int IDENTIFIER = 13;
  public static final int LPAREN = 8;
  public static final int RBRACE = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IN",
  "IF",
  "ELSE",
  "COMMA",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "EQ",
  "PLUS",
  "STRING_LITERAL",
  "IDENTIFIER"
  };
}

